export const registerAccountKeywords = {
    headTitle: {
        en: "Create Your Account | Airport Pickups Edinburgh Transfers",
        tr: "Hesabınızı Oluşturun | Airport Pickups Edinburgh Transfers",
        zh: "创建账户 | Airport Pickups Edinburgh Transfers",
        ar: "إنشاء حسابك | Airport Pickups Edinburgh Transfers",
        ru: "Создайте аккаунт | Airport Pickups Edinburgh Transfers",
        es: "Crea tu cuenta | Airport Pickups Edinburgh Transfers",
        it: "Crea il tuo account | Airport Pickups Edinburgh Transfers",
    },
    keywords: {
        en: "register Airport Pickups Edinburgh, create account, airport transfer sign up, book taxi online, travel account Edinburgh",
        tr: "Airport Pickups Edinburgh kaydol, hesap oluştur, havaalanı transferi üyelik, online taksi rezervasyonu, Edinburgh seyahat hesabı",
        zh: "注册 Airport Pickups Edinburgh, 创建账户, 机场接送注册, 在线预订出租车, 爱丁堡旅行账户",
        ar: "تسجيل Airport Pickups Edinburgh, إنشاء حساب, الاشتراك في خدمة النقل من المطار, حجز تاكسي عبر الإنترنت, حساب سفر إدنبرة",
        ru: "регистрация Airport Pickups Edinburgh, создать аккаунт, регистрация трансфера из аэропорта, онлайн заказ такси, туристический аккаунт Эдинбург",
        es: "registrarse en Airport Pickups Edinburgh, crear cuenta, registro para traslado al aeropuerto, reservar taxi online, cuenta de viajes Edimburgo",
        it: "registrati su Airport Pickups Edinburgh, crea account, iscrizione transfer aeroporto, prenota taxi online, account viaggio Edimburgo",
    },
    metaDescription: {
        en: "Register for a free Airport Pickups Edinburgh account to book airport transfers easily. Save your travel details and enjoy a faster, more convenient experience in Edinburgh.",
        tr: "Havaalanı transferlerinizi kolayca rezerve etmek için ücretsiz Airport Pickups Edinburgh hesabınızı oluşturun. Seyahat bilgilerinizi kaydedin, Edinburgh'da daha hızlı ve konforlu deneyim yaşayın.",
        zh: "注册免费 Airport Pickups Edinburgh 账户，轻松预订机场接送服务。保存您的旅行信息，在爱丁堡享受更快捷便利的体验。",
        ar: "سجل حسابًا مجانيًا مع Airport Pickups Edinburgh لحجز خدمات النقل من المطار بسهولة. احفظ تفاصيل رحلتك واستمتع بتجربة أسرع وأكثر راحة في إدنبرة.",
        ru: "Зарегистрируйтесь в Airport Pickups Edinburgh бесплатно, чтобы легко бронировать трансферы из аэропорта. Сохраняйте данные поездок и наслаждайтесь комфортом в Эдинбурге.",
        es: "Regístrate gratis en Airport Pickups Edinburgh para reservar traslados al aeropuerto fácilmente. Guarda tus datos de viaje y disfruta de una experiencia más rápida y cómoda en Edimburgo.",
        it: "Crea gratuitamente un account Airport Pickups Edinburgh per prenotare facilmente i transfer aeroportuali. Salva i tuoi dati di viaggio e goditi un'esperienza più comoda e veloce a Edimburgo.",
    },
};
export const registerAccountResultsKeywords = {
    headTitle: {
        tr: "Hesap Kaydı Başarılı | Airport Pickups Edinburgh Transfers",
        zh: "账户注册成功 | Airport Pickups Edinburgh Transfers",
        ar: "تم تسجيل الحساب بنجاح | Airport Pickups Edinburgh Transfers",
        ru: "Регистрация аккаунта успешна | Airport Pickups Edinburgh Transfers",
        es: "Registro de cuenta exitoso | Airport Pickups Edinburgh Transfers",
        it: "Registrazione account completata | Airport Pickups Edinburgh Transfers",
    },
    keywords: {
        en: "Airport Pickups Edinburgh account created, registration successful, transfer confirmation, travel account success, airport taxi account",
        tr: "Airport Pickups Edinburgh hesabı oluşturuldu, kayıt başarılı, transfer onayı, seyahat hesabı başarı, havaalanı taksi hesabı",
        zh: "Airport Pickups Edinburgh 账户已创建, 注册成功, 接送确认, 旅行账户成功, 机场出租车账户",
        ar: "تم إنشاء حساب Airport Pickups Edinburgh, التسجيل ناجح, تأكيد النقل, نجاح حساب السفر, حساب تاكسي المطار",
        ru: "Аккаунт Airport Pickups Edinburgh создан, регистрация успешна, подтверждение трансфера, аккаунт для поездок, аккаунт такси из аэропорта",
        es: "Cuenta de Airport Pickups Edinburgh creada, registro exitoso, confirmación de traslado, cuenta de viaje exitosa, cuenta de taxi de aeropuerto",
        it: "Account Airport Pickups Edinburgh creato, registrazione riuscita, conferma transfer, account di viaggio attivo, account taxi aeroporto",
    },
    metaDescription: {
        en: "Your Airport Pickups Edinburgh account has been successfully registered. You can now manage bookings, save travel preferences, and enjoy smooth airport transfers in Edinburgh.",
        tr: "Airport Pickups Edinburgh hesabınız başarıyla kaydedildi. Artık rezervasyonlarınızı yönetebilir, seyahat tercihlerinizi kaydedebilir ve Edinburgh'da sorunsuz havaalanı transferleri yaşayabilirsiniz.",
        zh: "您的 Airport Pickups Edinburgh 账户已成功注册。现在您可以管理预订，保存出行偏好，享受在爱丁堡顺畅的机场接送服务。",
        ar: "تم تسجيل حسابك في Airport Pickups Edinburgh بنجاح. يمكنك الآن إدارة الحجوزات، وحفظ تفضيلات السفر، والاستمتاع بخدمة نقل مريحة من المطار في إدنبرة.",
        ru: "Ваш аккаунт Airport Pickups Edinburgh успешно зарегистрирован. Теперь вы можете управлять бронированиями, сохранять предпочтения поездок и наслаждаться трансферами в Эдинбурге.",
        es: "Tu cuenta de Airport Pickups Edinburgh se ha registrado con éxito. Ahora puedes gestionar reservas, guardar tus preferencias y disfrutar de traslados cómodos en Edimburgo.",
        it: "Il tuo account Airport Pickups Edinburgh è stato registrato con successo. Ora puoi gestire le prenotazioni, salvare le preferenze di viaggio e goderti transfer comodi a Edimburgo.",
    },
};
